development:
  adapter: 'mysql2'
  host: '127.0.0.1'
  database: 'white_pepper'
  user: 'suki60'
  password: '1234'

production:
    adapter: 'postgres'
    host: ENV['HOST']
    database: ENV['DATABASE']
    user: ENV['USER']
    password: ENV['PASSWORD']
    port: ENV['PORT']
