development:
  adapter: 'mysql2'
  host: '127.0.0.1'
  database: 'white_pepper'
  user: 'suki60'
  password: '1234'

production:
    adapter: 'postgres'
    host: 'ec2-50-17-227-28.compute-1.amazonaws.com'
    database: 'd3ddmjh3ameilj'
    user: kxutcxrmuehsxw
    password: e3eb370983b819f91f071542e4f36387f6613826136d2fa541fe8e388aef8577
    port: '5432'
